name: 'PNPM install'

description: "Installs PNPM & runs `pnpm install`"

runs:
    using: "composite"
    steps:
        -   run: git rev-parse HEAD
            shell: sh

        -   run: git rev-parse HEAD~1
            continue-on-error: true
            shell: sh

        -   name: Setup NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: '20'

        -   name: Install PNPM
            uses: pnpm/action-setup@v2
            with:
                version: 8
                run_install: false

        -   run: pnpm --version
            shell: sh

        -   name: Get pnpm store directory
            id: pnpm-cache
            shell: sh
            run: |
                echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

        -   name: Cache PNPM store directory
            uses: actions/cache@v4
            with:
                path: |
                    /home/runner/.cache/Cypress
                    ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                    ${{ runner.os }}-pnpm-store-

        -   run: pnpm install
            shell: sh
