name: CI/CD

on:
    push:
        branches:
            # - renovate/* - do not build renovate branches as they'll be built by PRs
            - main
    #            - feature/*
    #            - bugfix/*
    #            - improvement/*
    #            - personal/*
    pull_request:

jobs:

    #    pnpm-cache:
    #        runs-on: ubuntu-latest
    #        steps:
    #            -   name: Checkout repository
    #                uses: actions/checkout@v4
    #                with:
    #                    fetch-depth: 0
    #
    #            -   uses: ./.github/actions/pnpm

    build-and-lint:
        #        needs: pnpm-cache
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   uses: ./.github/actions/pnpm

            -   name: Derive appropriate SHAs for base and head for `nx affected` commands
                uses: nrwl/nx-set-shas@v4

            -   name: nx build & lint affected
                env:
                    # https://stackoverflow.com/a/73429959/1975086, https://github.com/angular/angular/issues/38216
                    BAZEL_TARGET: "1"
                # https://stackoverflow.com/questions/73876647/using-nx-run-many-shows-another-process-with-id-is-currently-running-ngcc
                # BE AWARE: Adding PARALLEL options may cause build to pass when it should have been failed
                run: pnpm run nx affected --target=build,lint --base=${{ env.NX_BASE }} --parallel=8


    e2e-cypress:
        #        needs: pnpm-cache
        runs-on: ubuntu-latest
        env:
            GCLOUD_PROJECT: demo-local-sneat-app
            FIREBASE_AUTH_EMULATOR_HOST: 127.0.0.1:9099
            FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   uses: sneat-co/sneat-go@main

            -   name: Install latest Chrome
                uses: browser-actions/setup-chrome@v1
                with:
                    chrome-version: latest

            -   name: Cache firebase emulators
                uses: actions/cache@v4
                with:
                    path: /home/runner/.cache/firebase/emulators
                    key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('/home/runner/.cache/firebase/emulators/**') }}
                continue-on-error: true

            -   name: Install Firebase Tools
                #                run: curl -Lo ./firebase_bin https://firebase.tools/bin/linux/v12.9.1
                run: curl -sL https://firebase.tools | bash
                #        run: pnpm install -g firebase-tools

            -   uses: ./.github/actions/pnpm


            # Running pnpm install --force bellow because at the moment, @angular/fire is not supporting Angular 17.
            # It can be removed once @angular/fire is updated to 17 as well.
            #            -   name: Run pnpm install
            #                run: pnpm install --force

            -   name: Run emulators
                run: |
                    pnpm run firebase-emulators:ci &
                    sleep 10

            -   name: Build and serve application
                run: |
                    pnpm run cy:serve:ci &
                    sleep 5

            -   name: Run e2e tests
                uses: cypress-io/github-action@v6
                with:
                    command: pnpm run cy:test:ci
                    wait-on: 'http://localhost:4205'
                    wait-on-timeout: 120

    e2e-playwright:
        name: Playwright tests
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-node@v4
                with:
                    node-version: lts/*

            -   name: Install dependencies
                run: npm install -g pnpm && pnpm install

            -   name: Install Playwright Browsers
                run: pnpm exec playwright install chromium --with-deps

            -   name: Run Playwright tests
                run: pnpm exec playwright test

            -   uses: actions/upload-artifact@v4
                if: always()
                with:
                    name: playwright-report
                    path: playwright-report/
                    retention-days: 30
